"""initial_schema

Revision ID: 97b1f90cc9d3
Revises: 
Create Date: 2026-03-25 08:38:48.359462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '97b1f90cc9d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('files',
    sa.Column('filename', sa.String(length=512), nullable=False, comment='Sanitised filename used for storage key.'),
    sa.Column('original_filename', sa.String(length=512), nullable=False, comment='Original filename as uploaded by the user.'),
    sa.Column('content_type', sa.String(length=255), nullable=False, comment='MIME content type.'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes.'),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of file contents.'),
    sa.Column('storage_key', sa.String(length=1024), nullable=False, comment='Object key in MinIO.'),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True, comment='User or API key that uploaded the file.'),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False, comment='Processing status.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp.'),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True, comment='When processing began.'),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True, comment='When processing finished.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_content_type', 'files', ['content_type'], unique=False)
    op.create_index('ix_files_created_at', 'files', ['created_at'], unique=False)
    op.create_index('ix_files_sha256_hash', 'files', ['sha256_hash'], unique=False)
    op.create_index('ix_files_status', 'files', ['status'], unique=False)
    op.create_table('llm_requests',
    sa.Column('caller_service', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fallback_from', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_requests_caller_service', 'llm_requests', ['caller_service'], unique=False)
    op.create_index('ix_llm_requests_created_at', 'llm_requests', ['created_at'], unique=False)
    op.create_index('ix_llm_requests_provider', 'llm_requests', ['provider'], unique=False)
    op.create_index('ix_llm_requests_purpose', 'llm_requests', ['purpose'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Lowercase tag name.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description.'),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='Whether this tag was created by the system (not user).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('file_tags',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.String(length=255), nullable=True, comment='User or system that assigned the tag.'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    op.create_table('processed_documents',
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False, comment='One of: technical, business, operational, research, communication, reference.'),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('frontmatter', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('processing_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processed_documents_category', 'processed_documents', ['category'], unique=False)
    op.create_index('ix_processed_documents_embedding', 'processed_documents', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_processed_documents_is_current'), 'processed_documents', ['is_current'], unique=False)
    op.create_index('ix_processed_documents_search_vector', 'processed_documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_processed_documents_source_current', 'processed_documents', ['source_file_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_processed_documents_source_file_id'), 'processed_documents', ['source_file_id'], unique=False)
    op.create_table('citations',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('source_locator', sa.VARCHAR(length=255), nullable=False),
    sa.Column('quote_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['processed_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'citation_index', name='uq_citation_doc_index')
    )
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    op.create_index('ix_citations_source_file_id', 'citations', ['source_file_id'], unique=False)
    op.create_table('diff_logs',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('diff_type', sa.VARCHAR(length=30), nullable=False, comment='One of: initial_processing, reprocessing, human_edit, agent_edit.'),
    sa.Column('before_text', sa.Text(), nullable=True, comment='Content before the change (null for initial processing).'),
    sa.Column('after_text', sa.Text(), nullable=False, comment='Content after the change.'),
    sa.Column('justification', sa.Text(), nullable=False, comment='Reason for the change.'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional structured data about the diff (e.g. chunk delta stats).'),
    sa.Column('created_by', sa.VARCHAR(length=255), server_default='system', nullable=False, comment='User, API key, or service that made the change.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['processed_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diff_logs_created_at', 'diff_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_diff_logs_document_id'), 'diff_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_diff_logs_source_file_id'), 'diff_logs', ['source_file_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_locator', sa.VARCHAR(length=255), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['processed_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_doc_index')
    )
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_diff_logs_source_file_id'), table_name='diff_logs')
    op.drop_index(op.f('ix_diff_logs_document_id'), table_name='diff_logs')
    op.drop_index('ix_diff_logs_created_at', table_name='diff_logs')
    op.drop_table('diff_logs')
    op.drop_index('ix_citations_source_file_id', table_name='citations')
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_processed_documents_source_file_id'), table_name='processed_documents')
    op.drop_index('ix_processed_documents_source_current', table_name='processed_documents')
    op.drop_index('ix_processed_documents_search_vector', table_name='processed_documents', postgresql_using='gin')
    op.drop_index(op.f('ix_processed_documents_is_current'), table_name='processed_documents')
    op.drop_index('ix_processed_documents_embedding', table_name='processed_documents', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_processed_documents_category', table_name='processed_documents')
    op.drop_table('processed_documents')
    op.drop_table('file_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_llm_requests_purpose', table_name='llm_requests')
    op.drop_index('ix_llm_requests_provider', table_name='llm_requests')
    op.drop_index('ix_llm_requests_created_at', table_name='llm_requests')
    op.drop_index('ix_llm_requests_caller_service', table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_index('ix_files_status', table_name='files')
    op.drop_index('ix_files_sha256_hash', table_name='files')
    op.drop_index('ix_files_created_at', table_name='files')
    op.drop_index('ix_files_content_type', table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
